[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
tanaid = { path = "crates/tanaid", version = "0.1.0" }
tanaid-tk = { path = "crates/tanaid-tk", version = "0.1.0" }
winit = "0.30"

[workspace.lints.rust]
warnings = "deny"

[profile.release]
debug = true
