[workspace]
members = ["crates/tanaid-wasm"]

[package]
name = "tanaid"
version = "0.1.0"
edition = "2024"

[features]
default = ["cli"]
cli = ["dep:clap", "dep:reedline"]

[[bin]]
name = "tanaid"
path = "src/main.rs"
required-features = ["cli"]

[profile.release]
debug = true

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-Wl,--no-rosegment"]

[dependencies]
clap = { version = "4", features = ["derive"], optional = true }
reedline = { version = "0.48.0", optional = true }
lru = "0.18.0"
regex = "1.12.4"

[dev-dependencies]
