[package]
name = "tanaid-tk"
description = "experimental tk features for tanaid"
license = "MPL-2.0"
edition.workspace = true
version.workspace = true
publish = true

[dependencies]
indexmap = "2.14.0"
pollster = { workspace = true, features = ["macro"] }
regex = { workspace = true }
tanaid = { workspace = true }
vello = "0.10.0"
winit = { workspace = true }

[lints]
workspace = true
