use std::{
  cmp::Reverse,
  collections::{BinaryHeap, HashSet},
  sync::mpsc::{Receiver, RecvTimeoutError},
  thread::sleep,
  time::{Duration, Instant},
};

use crate::{
  eval::{EvalContext, TimerAction},
  eval_error::EvalError,
};

type TimerId = usize;

pub struct EventLoop {
  pending_timers: HashSet<TimerId>,
  timer_queue: BinaryHeap<Reverse<(Instant, TimerId)>>,
  stop_requested_rx: Option<Receiver<()>>,
}

impl EventLoop {
  pub fn new() -> EventLoop {
    EventLoop {
      pending_timers: HashSet::new(),
      timer_queue: BinaryHeap::new(),
      stop_requested_rx: None,
    }
  }

  pub fn with_stop_requested_rx(mut self, stop_requested_rx: Receiver<()>) -> EventLoop {
    self.stop_requested_rx = Some(stop_requested_rx);
    self
  }

  pub fn apply_actions(&mut self, actions: Vec<TimerAction>) {
    for action in actions {
      match action {
        TimerAction::Start { timer_id, delay_ms } => {
          self.timer_queue.push(Reverse((
            Instant::now() + Duration::from_millis(delay_ms),
            timer_id,
          )));
          self.pending_timers.insert(timer_id);
        }
        TimerAction::Cancel { timer_id } => {
          self.pending_timers.remove(&timer_id);
        }
      }
    }
  }

  pub fn count_pending(&self) -> usize {
    self.pending_timers.len()
  }

  pub fn take_elapsed(&mut self) -> Result<Option<TimerId>, EvalError> {
    while self
      .timer_queue
      .peek()
      .is_some_and(|Reverse((fires_at, _))| *fires_at <= Instant::now())
    {
      let Reverse((_, timer_id)) = self.timer_queue.pop().unwrap();
      if !self.pending_timers.contains(&timer_id) {
        // cancelled
        continue;
      }
      return Ok(Some(self.pending_timers.take(&timer_id).unwrap()));
    }
    Ok(None)
  }

  pub fn next_deadline(&mut self) -> Option<Instant> {
    while let Some(Reverse((fires_at, timer_id))) = self.timer_queue.peek() {
      if self.pending_timers.contains(&timer_id) {
        return Some(fires_at.clone());
      }
      self.timer_queue.pop();
    }

    None
  }

  /// Fire up to one elapsed timer and enqueue any newly-generated timer actions.
  pub fn poll(&mut self, context: &mut EvalContext) -> Result<(), EvalError> {
    self.apply_actions(context.take_timer_actions());

    if let Some(timer_id) = self.take_elapsed()? {
      let result = context.fire_timer(timer_id);
      self.apply_actions(context.take_timer_actions());
      result?;
    }

    Ok(())
  }

  /// Run the event loop until all pending timers are fired, or the loop is interrupted.
  pub fn run(
    &mut self,
    context: &mut EvalContext,
    mut loop_callback: impl FnMut() -> Result<(), EvalError>,
  ) -> Result<(), EvalError> {
    // handle any queued timer actions
    self.apply_actions(context.take_timer_actions());
    loop_callback()?;

    while self.count_pending() > 0 {
      // fire elapsed timers
      while let Some(timer_id) = self.take_elapsed()? {
        context.fire_timer(timer_id)?;
        // handle new timer actions generated by this timer
        self.apply_actions(context.take_timer_actions());
        loop_callback()?;
      }

      // wait for nextmost timer
      if let Some(next_deadline) = self.next_deadline() {
        let next_wait = next_deadline.saturating_duration_since(Instant::now());
        if let Some(stop_requested_rx) = &self.stop_requested_rx {
          // interruptible wait
          match stop_requested_rx.recv_timeout(next_wait) {
            // stop requested
            Ok(()) => return Ok(()),
            // wait complete
            Err(RecvTimeoutError::Timeout) => {}
            // error
            Err(e) => return Err(EvalError::Generic(e.to_string())),
          }
        } else {
          // non-interruptible wait
          sleep(next_wait);
        }
      }
    }

    Ok(())
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::{eval, parser};
  use std::{cell::RefCell, rc::Rc, sync::mpsc};

  fn context_with_output() -> (EvalContext, Rc<RefCell<String>>) {
    let output = Rc::new(RefCell::new(String::new()));
    let output_sink = output.clone();
    let context = EvalContext::new().with_stdout(Rc::new(move |text| {
      output_sink.borrow_mut().push_str(text);
      Ok(())
    }));
    (context, output)
  }

  fn eval_source(source: &str, context: &mut EvalContext) {
    eval::eval(&parser::parse(source).unwrap(), context).unwrap();
  }

  #[test]
  fn fires_timers_in_deadline_order() {
    let (mut context, output) = context_with_output();
    eval_source("after 1 {puts later}; after 0 {puts sooner}", &mut context);

    EventLoop::new().run(&mut context, || Ok(())).unwrap();

    assert_eq!(*output.borrow(), "sooner\nlater\n");
  }

  #[test]
  fn handles_nested_and_cancelled_timers() {
    let (mut context, output) = context_with_output();
    eval_source(
      "
        after 0 {after 0 {puts nested}}
        set cancelled [after 0 {puts cancelled}]
        after cancel $cancelled
      ",
      &mut context,
    );

    EventLoop::new().run(&mut context, || Ok(())).unwrap();

    assert_eq!(*output.borrow(), "nested\n");
  }

  #[test]
  fn poll_yields_before_newly_scheduled_timer() {
    let (mut context, output) = context_with_output();
    let mut event_loop = EventLoop::new();
    eval_source("after 0 {puts first; after 0 {puts second}}", &mut context);

    event_loop.poll(&mut context).unwrap();
    assert_eq!(*output.borrow(), "first\n");

    event_loop.poll(&mut context).unwrap();
    assert_eq!(*output.borrow(), "first\nsecond\n");
  }

  #[test]
  fn poll_preserves_other_timers_after_error() {
    let (mut context, output) = context_with_output();
    let mut event_loop = EventLoop::new();
    eval_source(
      "after 0 {undefined_command}; after 0 {puts second}",
      &mut context,
    );

    assert!(event_loop.poll(&mut context).is_err());
    event_loop.poll(&mut context).unwrap();

    assert_eq!(*output.borrow(), "second\n");
  }

  #[test]
  fn remains_reusable_after_timer_error() {
    let mut context = EvalContext::new();
    let mut event_loop = EventLoop::new();
    eval_source("after 0 {undefined_command}", &mut context);

    assert!(event_loop.run(&mut context, || Ok(())).is_err());
    assert!(event_loop.run(&mut context, || Ok(())).is_ok());
  }

  #[test]
  fn exits_on_stop_request_without_firing_remaining_timers() {
    let (mut context, output) = context_with_output();
    eval_source(
      "after 0 {puts elapsed}; after 10000 {puts remaining}",
      &mut context,
    );

    let (stop_tx, stop_rx) = mpsc::channel();
    stop_tx.send(()).unwrap();

    EventLoop::new()
      .with_stop_requested_rx(stop_rx)
      .run(&mut context, || Ok(()))
      .unwrap();

    assert_eq!(*output.borrow(), "elapsed\n");
  }

  #[test]
  fn fires_timers_while_stop_channel_is_idle() {
    let (mut context, output) = context_with_output();
    eval_source("after 20 {puts fired}", &mut context);

    let (_stop_tx, stop_rx) = mpsc::channel();

    EventLoop::new()
      .with_stop_requested_rx(stop_rx)
      .run(&mut context, || Ok(()))
      .unwrap();

    assert_eq!(*output.borrow(), "fired\n");
  }

  #[test]
  fn errors_when_stop_channel_disconnects() {
    let mut context = EvalContext::new();
    eval_source("after 10000 {puts fired}", &mut context);

    let (stop_tx, stop_rx) = mpsc::channel();
    drop(stop_tx);

    let result = EventLoop::new()
      .with_stop_requested_rx(stop_rx)
      .run(&mut context, || Ok(()));

    assert!(result.is_err());
  }
}
