use std::{
  cmp::Reverse,
  collections::{BinaryHeap, HashSet},
  thread::sleep,
  time::{Duration, Instant},
};

use crate::{
  eval::{EvalContext, TimerAction},
  eval_error::EvalError,
};

type TimerId = usize;

pub struct EventLoop {
  pending_timers: HashSet<TimerId>,
  timer_queue: BinaryHeap<Reverse<(Instant, TimerId)>>,
}

impl EventLoop {
  pub fn new() -> EventLoop {
    EventLoop {
      pending_timers: HashSet::new(),
      timer_queue: BinaryHeap::new(),
    }
  }

  fn apply_actions(&mut self, actions: Vec<TimerAction>) {
    for action in actions {
      match action {
        TimerAction::Start { timer_id, delay_ms } => {
          self.timer_queue.push(Reverse((
            Instant::now() + Duration::from_millis(delay_ms),
            timer_id,
          )));
          self.pending_timers.insert(timer_id);
        }
        TimerAction::Cancel { timer_id } => {
          self.pending_timers.remove(&timer_id);
        }
      }
    }
  }

  /// Fires every timer whose deadline has elapsed, then returns the deadline of
  /// the nextmost pending timer, or None when no timers are left.
  ///
  /// Hosts that own their own event loop (a windowing system, the browser)
  /// drive the timers by polling instead of calling [`EventLoop::run`].
  pub fn poll(&mut self, context: &mut EvalContext) -> Result<Option<Instant>, EvalError> {
    // handle any queued timer actions
    self.apply_actions(context.take_timer_actions());

    while let Some(&Reverse((fires_at, timer_id))) = self.timer_queue.peek() {
      if !self.pending_timers.contains(&timer_id) {
        // cancelled
        self.timer_queue.pop();
        continue;
      }
      if fires_at > Instant::now() {
        break;
      }

      self.timer_queue.pop();
      let result = context.fire_timer(timer_id);
      self.pending_timers.remove(&timer_id);

      // handle new timer actions generated by this timer
      self.apply_actions(context.take_timer_actions());
      result?;
    }

    Ok(
      self
        .timer_queue
        .peek()
        .map(|Reverse((fires_at, _))| *fires_at),
    )
  }

  pub fn run(&mut self, context: &mut EvalContext) -> Result<(), EvalError> {
    while let Some(fires_at) = self.poll(context)? {
      // wait for nextmost timer
      let wait_time = fires_at.saturating_duration_since(Instant::now());
      if !wait_time.is_zero() {
        sleep(wait_time);
      }
    }

    Ok(())
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::{eval, parser};
  use std::{cell::RefCell, rc::Rc};

  fn context_with_output() -> (EvalContext, Rc<RefCell<String>>) {
    let output = Rc::new(RefCell::new(String::new()));
    let output_sink = output.clone();
    let context = EvalContext::new().with_stdout(Rc::new(move |text| {
      output_sink.borrow_mut().push_str(text);
      Ok(())
    }));
    (context, output)
  }

  fn eval_source(source: &str, context: &mut EvalContext) {
    eval::eval(&parser::parse(source).unwrap(), context).unwrap();
  }

  #[test]
  fn fires_timers_in_deadline_order() {
    let (mut context, output) = context_with_output();
    eval_source("after 1 {puts later}; after 0 {puts sooner}", &mut context);

    EventLoop::new().run(&mut context).unwrap();

    assert_eq!(*output.borrow(), "sooner\nlater\n");
  }

  #[test]
  fn handles_nested_and_cancelled_timers() {
    let (mut context, output) = context_with_output();
    eval_source(
      "
        after 0 {after 0 {puts nested}}
        set cancelled [after 0 {puts cancelled}]
        after cancel $cancelled
      ",
      &mut context,
    );

    EventLoop::new().run(&mut context).unwrap();

    assert_eq!(*output.borrow(), "nested\n");
  }

  #[test]
  fn remains_reusable_after_timer_error() {
    let mut context = EvalContext::new();
    let mut event_loop = EventLoop::new();
    eval_source("after 0 {undefined_command}", &mut context);

    assert!(event_loop.run(&mut context).is_err());
    assert!(event_loop.run(&mut context).is_ok());
  }
}
