//! Mapping from winit keys to Tk/X11 keysym names (as reported by `%K`).
//! This file was generated by Claude Opus 5.5

use winit::keyboard::{Key, KeyLocation, NamedKey};

/// Returns the Tk keysym name for a key, or `""` if it has none.
pub fn key_detail(key: &Key, location: KeyLocation) -> String {
  match key {
    Key::Named(named) => named_keysym(*named, location).to_string(),
    Key::Character(text) => {
      let mut chars = text.chars();
      match (chars.next(), chars.next()) {
        (Some(c), None) => char_keysym(c, location),
        _ => text.to_string(),
      }
    }
    Key::Unidentified(_) | Key::Dead(_) => String::new(),
  }
}

fn named_keysym(key: NamedKey, location: KeyLocation) -> &'static str {
  let right = location == KeyLocation::Right;
  if location == KeyLocation::Numpad {
    let kp = match key {
      NamedKey::Enter => Some("KP_Enter"),
      NamedKey::Tab => Some("KP_Tab"),
      NamedKey::Space => Some("KP_Space"),
      NamedKey::Home => Some("KP_Home"),
      NamedKey::End => Some("KP_End"),
      NamedKey::ArrowLeft => Some("KP_Left"),
      NamedKey::ArrowUp => Some("KP_Up"),
      NamedKey::ArrowRight => Some("KP_Right"),
      NamedKey::ArrowDown => Some("KP_Down"),
      NamedKey::PageUp => Some("KP_Prior"),
      NamedKey::PageDown => Some("KP_Next"),
      NamedKey::Clear => Some("KP_Begin"),
      NamedKey::Insert => Some("KP_Insert"),
      NamedKey::Delete => Some("KP_Delete"),
      NamedKey::F1 => Some("KP_F1"),
      NamedKey::F2 => Some("KP_F2"),
      NamedKey::F3 => Some("KP_F3"),
      NamedKey::F4 => Some("KP_F4"),
      _ => None,
    };
    if let Some(kp) = kp {
      return kp;
    }
  }

  match key {
    NamedKey::Shift if right => "Shift_R",
    NamedKey::Shift => "Shift_L",
    NamedKey::Control if right => "Control_R",
    NamedKey::Control => "Control_L",
    NamedKey::Alt if right => "Alt_R",
    NamedKey::Alt => "Alt_L",
    NamedKey::Super if right => "Super_R",
    NamedKey::Super => "Super_L",
    NamedKey::Meta if right => "Meta_R",
    NamedKey::Meta => "Meta_L",
    NamedKey::Hyper if right => "Hyper_R",
    NamedKey::Hyper => "Hyper_L",
    NamedKey::AltGraph => "ISO_Level3_Shift",
    NamedKey::CapsLock => "Caps_Lock",
    NamedKey::NumLock => "Num_Lock",
    NamedKey::ScrollLock => "Scroll_Lock",

    NamedKey::Enter => "Return",
    NamedKey::Tab => "Tab",
    NamedKey::Space => "space",
    NamedKey::ArrowDown => "Down",
    NamedKey::ArrowLeft => "Left",
    NamedKey::ArrowRight => "Right",
    NamedKey::ArrowUp => "Up",
    NamedKey::End => "End",
    NamedKey::Home => "Home",
    NamedKey::PageDown => "Next",
    NamedKey::PageUp => "Prior",

    NamedKey::Backspace => "BackSpace",
    NamedKey::Clear => "Clear",
    NamedKey::Copy => "XF86Copy",
    NamedKey::CrSel => "3270_CursorSelect",
    NamedKey::Cut => "XF86Cut",
    NamedKey::Delete => "Delete",
    NamedKey::EraseEof => "3270_EraseEOF",
    NamedKey::ExSel => "3270_ExSelect",
    NamedKey::Insert => "Insert",
    NamedKey::Paste => "XF86Paste",
    NamedKey::Redo => "Redo",
    NamedKey::Undo => "Undo",

    NamedKey::Attn => "3270_Attn",
    NamedKey::Cancel => "Cancel",
    NamedKey::ContextMenu => "Menu",
    NamedKey::Escape => "Escape",
    NamedKey::Execute => "Execute",
    NamedKey::Find => "Find",
    NamedKey::Help => "Help",
    NamedKey::Pause => "Pause",
    NamedKey::Play => "3270_Play",
    NamedKey::Select => "Select",
    NamedKey::ZoomIn => "XF86ZoomIn",
    NamedKey::ZoomOut => "XF86ZoomOut",

    NamedKey::BrightnessDown => "XF86MonBrightnessDown",
    NamedKey::BrightnessUp => "XF86MonBrightnessUp",
    NamedKey::Eject => "XF86Eject",
    NamedKey::LogOff => "XF86LogOff",
    NamedKey::Power | NamedKey::PowerOff => "XF86PowerOff",
    NamedKey::PrintScreen | NamedKey::Print => "Print",
    NamedKey::Hibernate => "XF86Hibernate",
    NamedKey::Standby => "XF86Standby",
    NamedKey::WakeUp => "XF86WakeUp",

    NamedKey::AllCandidates => "MultipleCandidate",
    NamedKey::Alphanumeric | NamedKey::Eisu => "Eisu_toggle",
    NamedKey::CodeInput => "Codeinput",
    NamedKey::Compose => "Multi_key",
    NamedKey::Convert => "Henkan_Mode",
    NamedKey::GroupFirst => "ISO_First_Group",
    NamedKey::GroupLast => "ISO_Last_Group",
    NamedKey::GroupNext => "ISO_Next_Group",
    NamedKey::GroupPrevious => "ISO_Prev_Group",
    NamedKey::ModeChange => "Mode_switch",
    NamedKey::NonConvert => "Muhenkan",
    NamedKey::PreviousCandidate => "PreviousCandidate",
    NamedKey::SingleCandidate => "SingleCandidate",
    NamedKey::HangulMode => "Hangul",
    NamedKey::HanjaMode => "Hangul_Hanja",
    NamedKey::JunjaMode => "Hangul_Jeonja",
    NamedKey::Hankaku => "Hankaku",
    NamedKey::Hiragana => "Hiragana",
    NamedKey::HiraganaKatakana => "Hiragana_Katakana",
    NamedKey::KanaMode => "Kana_Lock",
    NamedKey::KanjiMode => "Kanji",
    NamedKey::Katakana => "Katakana",
    NamedKey::Romaji => "Romaji",
    NamedKey::Zenkaku => "Zenkaku",
    NamedKey::ZenkakuHankaku => "Zenkaku_Hankaku",

    NamedKey::Close => "XF86Close",
    NamedKey::MailForward => "XF86MailForward",
    NamedKey::MailReply => "XF86Reply",
    NamedKey::MailSend => "XF86Send",
    NamedKey::MediaFastForward => "XF86AudioForward",
    NamedKey::MediaPause => "XF86AudioPause",
    NamedKey::MediaPlay | NamedKey::MediaPlayPause => "XF86AudioPlay",
    NamedKey::MediaRecord => "XF86AudioRecord",
    NamedKey::MediaRewind => "XF86AudioRewind",
    NamedKey::MediaStop => "XF86AudioStop",
    NamedKey::MediaTrackNext => "XF86AudioNext",
    NamedKey::MediaTrackPrevious => "XF86AudioPrev",
    NamedKey::MediaAudioTrack => "XF86AudioCycleTrack",
    NamedKey::RandomToggle => "XF86AudioRandomPlay",
    NamedKey::New => "XF86New",
    NamedKey::Open => "XF86Open",
    NamedKey::Save => "XF86Save",
    NamedKey::SpellCheck => "XF86Spell",
    NamedKey::Subtitle => "XF86Subtitle",
    NamedKey::SplitScreenToggle => "XF86SplitScreen",
    NamedKey::VideoModeNext => "XF86Next_VMode",

    NamedKey::AudioVolumeDown => "XF86AudioLowerVolume",
    NamedKey::AudioVolumeUp => "XF86AudioRaiseVolume",
    NamedKey::AudioVolumeMute => "XF86AudioMute",
    NamedKey::MicrophoneVolumeMute => "XF86AudioMicMute",

    NamedKey::LaunchApplication1 => "XF86MyComputer",
    NamedKey::LaunchApplication2 => "XF86Calculator",
    NamedKey::LaunchCalendar => "XF86Calendar",
    NamedKey::LaunchMail => "XF86Mail",
    NamedKey::LaunchMediaPlayer => "XF86Video",
    NamedKey::LaunchMusicPlayer => "XF86Music",
    NamedKey::LaunchPhone => "XF86Phone",
    NamedKey::LaunchScreenSaver => "XF86ScreenSaver",
    NamedKey::LaunchSpreadsheet => "XF86Excel",
    NamedKey::LaunchWebBrowser => "XF86WWW",
    NamedKey::LaunchWebCam => "XF86WebCam",
    NamedKey::LaunchWordProcessor => "XF86Word",
    NamedKey::BrowserBack => "XF86Back",
    NamedKey::BrowserFavorites => "XF86Favorites",
    NamedKey::BrowserForward => "XF86Forward",
    NamedKey::BrowserHome => "XF86HomePage",
    NamedKey::BrowserRefresh => "XF86Refresh",
    NamedKey::BrowserSearch => "XF86Search",
    NamedKey::BrowserStop => "XF86Stop",

    NamedKey::F1 => "F1",
    NamedKey::F2 => "F2",
    NamedKey::F3 => "F3",
    NamedKey::F4 => "F4",
    NamedKey::F5 => "F5",
    NamedKey::F6 => "F6",
    NamedKey::F7 => "F7",
    NamedKey::F8 => "F8",
    NamedKey::F9 => "F9",
    NamedKey::F10 => "F10",
    NamedKey::F11 => "F11",
    NamedKey::F12 => "F12",
    NamedKey::F13 => "F13",
    NamedKey::F14 => "F14",
    NamedKey::F15 => "F15",
    NamedKey::F16 => "F16",
    NamedKey::F17 => "F17",
    NamedKey::F18 => "F18",
    NamedKey::F19 => "F19",
    NamedKey::F20 => "F20",
    NamedKey::F21 => "F21",
    NamedKey::F22 => "F22",
    NamedKey::F23 => "F23",
    NamedKey::F24 => "F24",
    NamedKey::F25 => "F25",
    NamedKey::F26 => "F26",
    NamedKey::F27 => "F27",
    NamedKey::F28 => "F28",
    NamedKey::F29 => "F29",
    NamedKey::F30 => "F30",
    NamedKey::F31 => "F31",
    NamedKey::F32 => "F32",
    NamedKey::F33 => "F33",
    NamedKey::F34 => "F34",
    NamedKey::F35 => "F35",

    _ => "",
  }
}

fn char_keysym(c: char, location: KeyLocation) -> String {
  if location == KeyLocation::Numpad {
    let kp = match c {
      '0'..='9' => return format!("KP_{c}"),
      '+' => Some("KP_Add"),
      '-' => Some("KP_Subtract"),
      '*' => Some("KP_Multiply"),
      '/' => Some("KP_Divide"),
      '.' => Some("KP_Decimal"),
      ',' => Some("KP_Separator"),
      '=' => Some("KP_Equal"),
      ' ' => Some("KP_Space"),
      '\t' => Some("KP_Tab"),
      '\r' | '\n' => Some("KP_Enter"),
      _ => None,
    };
    if let Some(kp) = kp {
      return kp.to_string();
    }
  }

  let name = match c {
    ' ' => "space",
    '!' => "exclam",
    '"' => "quotedbl",
    '#' => "numbersign",
    '$' => "dollar",
    '%' => "percent",
    '&' => "ampersand",
    '\'' => "apostrophe",
    '(' => "parenleft",
    ')' => "parenright",
    '*' => "asterisk",
    '+' => "plus",
    ',' => "comma",
    '-' => "minus",
    '.' => "period",
    '/' => "slash",
    ':' => "colon",
    ';' => "semicolon",
    '<' => "less",
    '=' => "equal",
    '>' => "greater",
    '?' => "question",
    '@' => "at",
    '[' => "bracketleft",
    '\\' => "backslash",
    ']' => "bracketright",
    '^' => "asciicircum",
    '_' => "underscore",
    '`' => "grave",
    '{' => "braceleft",
    '|' => "bar",
    '}' => "braceright",
    '~' => "asciitilde",
    '\t' => "Tab",
    '\r' | '\n' => "Return",
    '\u{8}' => "BackSpace",
    '\u{1b}' => "Escape",
    '\u{7f}' => "Delete",
    '\u{a0}'..='\u{ff}' => LATIN1[c as usize - 0xa0],
    _ => return c.to_string(),
  };
  name.to_string()
}

/// X11 keysym names for U+00A0 through U+00FF.
const LATIN1: [&str; 96] = [
  "nobreakspace",
  "exclamdown",
  "cent",
  "sterling",
  "currency",
  "yen",
  "brokenbar",
  "section",
  "diaeresis",
  "copyright",
  "ordfeminine",
  "guillemotleft",
  "notsign",
  "hyphen",
  "registered",
  "macron",
  "degree",
  "plusminus",
  "twosuperior",
  "threesuperior",
  "acute",
  "mu",
  "paragraph",
  "periodcentered",
  "cedilla",
  "onesuperior",
  "masculine",
  "guillemotright",
  "onequarter",
  "onehalf",
  "threequarters",
  "questiondown",
  "Agrave",
  "Aacute",
  "Acircumflex",
  "Atilde",
  "Adiaeresis",
  "Aring",
  "AE",
  "Ccedilla",
  "Egrave",
  "Eacute",
  "Ecircumflex",
  "Ediaeresis",
  "Igrave",
  "Iacute",
  "Icircumflex",
  "Idiaeresis",
  "ETH",
  "Ntilde",
  "Ograve",
  "Oacute",
  "Ocircumflex",
  "Otilde",
  "Odiaeresis",
  "multiply",
  "Oslash",
  "Ugrave",
  "Uacute",
  "Ucircumflex",
  "Udiaeresis",
  "Yacute",
  "THORN",
  "ssharp",
  "agrave",
  "aacute",
  "acircumflex",
  "atilde",
  "adiaeresis",
  "aring",
  "ae",
  "ccedilla",
  "egrave",
  "eacute",
  "ecircumflex",
  "ediaeresis",
  "igrave",
  "iacute",
  "icircumflex",
  "idiaeresis",
  "eth",
  "ntilde",
  "ograve",
  "oacute",
  "ocircumflex",
  "otilde",
  "odiaeresis",
  "division",
  "oslash",
  "ugrave",
  "uacute",
  "ucircumflex",
  "udiaeresis",
  "yacute",
  "thorn",
  "ydiaeresis",
];

#[cfg(test)]
mod tests {
  use super::*;

  fn detail(key: Key) -> String {
    key_detail(&key, KeyLocation::Standard)
  }

  #[test]
  fn named_keys_map_to_tk_keysyms() {
    assert_eq!(detail(Key::Character("a".into())), "a");
    assert_eq!(detail(Key::Named(NamedKey::ArrowUp)), "Up");
    assert_eq!(detail(Key::Named(NamedKey::Enter)), "Return");
    assert_eq!(detail(Key::Named(NamedKey::Space)), "space");
    assert_eq!(detail(Key::Named(NamedKey::Backspace)), "BackSpace");
    assert_eq!(detail(Key::Named(NamedKey::PageUp)), "Prior");
    assert_eq!(detail(Key::Named(NamedKey::PageDown)), "Next");
    assert_eq!(detail(Key::Named(NamedKey::CapsLock)), "Caps_Lock");
    assert_eq!(detail(Key::Named(NamedKey::F12)), "F12");
    assert_eq!(detail(Key::Named(NamedKey::F35)), "F35");
    assert_eq!(
      detail(Key::Named(NamedKey::AudioVolumeUp)),
      "XF86AudioRaiseVolume"
    );
  }

  #[test]
  fn characters_map_to_keysym_names() {
    assert_eq!(detail(Key::Character("A".into())), "A");
    assert_eq!(detail(Key::Character("7".into())), "7");
    assert_eq!(detail(Key::Character(" ".into())), "space");
    assert_eq!(detail(Key::Character("!".into())), "exclam");
    assert_eq!(detail(Key::Character("@".into())), "at");
    assert_eq!(detail(Key::Character("[".into())), "bracketleft");
    assert_eq!(detail(Key::Character("~".into())), "asciitilde");
    assert_eq!(detail(Key::Character("é".into())), "eacute");
    assert_eq!(detail(Key::Character("ß".into())), "ssharp");
    assert_eq!(detail(Key::Character("λ".into())), "λ");
  }

  #[test]
  fn modifiers_distinguish_left_and_right() {
    let shift = Key::Named(NamedKey::Shift);
    assert_eq!(key_detail(&shift, KeyLocation::Left), "Shift_L");
    assert_eq!(key_detail(&shift, KeyLocation::Right), "Shift_R");
    let ctrl = Key::Named(NamedKey::Control);
    assert_eq!(key_detail(&ctrl, KeyLocation::Left), "Control_L");
    assert_eq!(key_detail(&ctrl, KeyLocation::Right), "Control_R");
    let alt = Key::Named(NamedKey::Alt);
    assert_eq!(key_detail(&alt, KeyLocation::Right), "Alt_R");
    let sup = Key::Named(NamedKey::Super);
    assert_eq!(key_detail(&sup, KeyLocation::Left), "Super_L");
  }

  #[test]
  fn numpad_keys_use_kp_names() {
    let kp = |key: Key| key_detail(&key, KeyLocation::Numpad);
    assert_eq!(kp(Key::Named(NamedKey::Enter)), "KP_Enter");
    assert_eq!(kp(Key::Named(NamedKey::ArrowUp)), "KP_Up");
    assert_eq!(kp(Key::Named(NamedKey::PageDown)), "KP_Next");
    assert_eq!(kp(Key::Named(NamedKey::NumLock)), "Num_Lock");
    assert_eq!(kp(Key::Character("0".into())), "KP_0");
    assert_eq!(kp(Key::Character("9".into())), "KP_9");
    assert_eq!(kp(Key::Character("+".into())), "KP_Add");
    assert_eq!(kp(Key::Character(".".into())), "KP_Decimal");
  }
}
